### ISSUE TITLE
NEWMA statistic initial spike

### ISSUE THREAD

**Issue by tylermanning** [lightonai/newma#1]
Is it expected that the NEWMA statistic always spikes initially regardless of the number of change points? I've been running many tests using your example, and it always seems to have a similar distribution. 

For example using a data stream with `gd.stream_GMM(d=15, nb_change=10, n=1000)`:
![image](https://user-images.githubusercontent.com/16857213/75388800-8b703b80-58b3-11ea-93af-8d92bd13ffb1.png)

Same thing if there are zero change points (still using a GMM as above but no changes):
![image](https://user-images.githubusercontent.com/16857213/75388937-c07c8e00-58b3-11ea-925a-4c9570c8e5ed.png)

I even tried just 1-D noise:
`mu, sigma = 0, 0.1`
`X = np.random.normal(mu, sigma, 10000).reshape(-1,1)`
And it still gives the same characteristic spike before settling:
![image](https://user-images.githubusercontent.com/16857213/75389329-587a7780-58b4-11ea-9ccd-77236e2e8a8a.png)

**Comment by tylermanning** [comment]
Seems like a similar issue with a different method like ScanB. This statistic plot is run on data generated from `gd.stream_GMM(d=15, nb_change=10, n=1000)` so 10 change points every 1000 time steps:
![image](https://user-images.githubusercontent.com/16857213/75392900-fe30e500-58ba-11ea-852c-1fbcbad1ba40.png)

Same as above, however, it seems upon closer look, that if I zoom in the graph starting at `t=1000` so at the first change point, the statistic resembles more what is expected from the paper:
![image](https://user-images.githubusercontent.com/16857213/75393029-3fc19000-58bb-11ea-96bd-3c25d1ca34ca.png)

**Comment by iacolippo** [comment]
Hi Tyler, that's because of initialization. Since it's a no-prior-knowledge method, the statistics needs some time to stabilize before it can detect a change.

If you know the in-control value and you initialize (`init_sample` parameter) with that, the initialization period duration should drop significantly. Because of the scale of the statistics, if you don't remove the first points from the plot, it's hard to see the actual changes detected.

In our paper https://arxiv.org/abs/1805.08061 we have an expression for this error, look at E_init in Lemma 6 Appendix 2.

**Comment by nkeriven** [comment]
Hi Taylor,

sorry for not getting back to you earlier on this, I was away.
Indeed all "window-based" algorithms like NEWMA or Scan-B have an "initialization period" where they will basically compute nonsensical stuff (usually a large spike), until the effects of the initialization become negligible. For Scan-B it is very easy to understand : if you haven't seen enough data to fill the time-windows that are compared together, the comparison itself does not make sense. I think by default the windows are filled with zeros, but one should expect to start the detection only after enough data have been seen to get rid of them. Same thing for NEWMA, the detection stats are initialized with a certain default value that does not really make sense, so the detection should only start after a certain time (roughly a few times the window size).

A way to remedy this is to first run the algorithm on a few training data, just to fill the windows with actual data for scan-B and initialize the stats in NEWMA with something that makes sense, before the actual run. You may still have an initial spike (but with a normal amplitude) if the training data has a different distribution. Another way to handle this is by giving the parameter "init_vec" in NEWMA an initial value that makes sense, but it is usually simpler to just run it on a few training data.

Cheers

Nicolas

**Comment by tylermanning** [comment]
Thanks for the information from both of you. Somehow I missed the discussion of initialization in the paper. 

This fact explains why you exclude the first 10n detection statistic/ground truth results when calculating the performance right? E.g. this part:
```
# compute performance metrics
detection_stat = np.array([i[0] for i in detector.stat_stored])[int(10 * n):]  # padding
online_th = np.array([i[1] for i in detector.stat_stored])[int(10 * n):]
ground_truth = ground_truth[int(10 * n):]
```

**Comment by iacolippo** [comment]
Happy to help! And yes, that is the reason why we exclude the first `10*n` samples.
